language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
install:
  - pip freeze > requirements.txt
  
#  install:
#    - pip install -r requirements.txt
  
#  script:
#    - pytest --cov-report term --cov=backend backend/UnitTests/ 

- stage: sonarcloud
      name: "SolarCloud Scan"
addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "travis encrypt da419e2499ff80dcf0e499918fe7d36e8e2361c6"
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  
script:
  - echo "Hello, World!"
  
# # allow gui output
services:
  - xvfb
  

