language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
install:
   - pip freeze > requirements.txt
   - pip install coverage
dist: xenial
script:
  - python3 HelloWorld.py
  - coverage run HelloWorld.py
after_success:
 - coverage report -m
 - coverage xml 


addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "v0LiuG1dJnzOMNrBU139ptymqdmLgZUW4AfTvtE4MTZFXf2a2qNjxU7nJkW9Ui5/8yz02nC6T+NNNhIpJr0XMRIYJpNKlKPJZS4OkX1vJ8t3xoRQJFhQRnUaBZuY8ip2cbcaPLSWcWGOCFzKkJpZqXH2Rr1+RcazSJHkXYfc1UNs/pThB0jtJ0rF/GdzFpVdUbW9T/5HAKRCwrYydmW2o/NX5CBODsYKx8WDgvoGbeW8KHI8AFAIOeimM4oecKULbdTwRpmzDUsTTl8XiFIXb+KFxdcqDzSBd//jAqh1UpKwoeYQaX0HDIB+oowp1LnDB0VuOS2nc9+cWEXR1XRBfzBFfxRmA95SBiOn4uuUauX2wg/gFRgz1f5No5PH2lzfqKu6EzX3UkSMr78UodMqNCv6Vt0yJl/6m0CjCLu0bRdrsLBcfdlFZmBhOi2nFWk5NsK6nRvoLgY2hrWbDmAUHD6LD1WFYKJlzpq+XipWI8D0g2nCqGITaouxAp1IxD0OTZP0Gu/TiPqt/HauOgAQ5ohnSYCzfeyzqI9GWoPmXUYgXwmTRBIopFwKOLcVl2HD1XPUhBRkRCXGBgVTCpP4AviJZN4HU2mtKTC/+WmO4wHtb5uF5KQfdyTu0eUVxynsJtYHd0YAnaKXvzPk3hOu346iZx1qAuOF3j3DoCu6dc8="
      

script:
  - sonar-scanner








  

