language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
install:
  - pip freeze > requirements.txt

addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "travis encrypt 6f849c47811996c29e85fb4191a25c1c9e360a2a" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  
# script:
#   - - echo "Hello, World!"
  
  
# allow gui output
services:
  - xvfb
  

