language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
install:
  - pip freeze > requirements.txt
  
  
  
   dist: xenial
 
 addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "ef89423cc704ed1d452dec8fe4614af387e09def"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
# command to run tests
script:
  - echo "Hello, World!"
  
# allow gui output
services:
  - xvfb
  

