language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
install:
   - pip freeze > requirements.txt
   - pip install coverage
dist: xenial
script:
  - python3 HelloWorld.py
  - coverage run HelloWorld.py
after_success:
 - coverage report -m
 - coverage xml 


addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "GsorCnasLltYPa6BClT5pKyZU9M7ir9D+Aq+Y3tY1Zt2JthfbyA4K1nNMpeZFTtDSKZJzbtlXWZBzlXvDdHTdr1Pq6xGhUSwreGMzSy4OKEGJUg6kkz04DToWrmqmygliJPqWG4WpsZ4t6mfUCYFvjEKMOXI7l+SqO0/ekFiEtlzlHUTZFwBsJHaXUCPgZ5pBK1IzCzmNO9MmAoCfbJonoS6Mo86GtELZ9tCJH4/bVRORAFABDScDGOL6xxGk9tqy+osRl3eaGF+RPRL9bA93eQXeG5kFB3XaDWxg3olIf85yGrzFLlxgR+jvyXen1zinDrj4Uc2rnjGsq04Z1Noq13PE52x4/qq6Fls38XaNWeOEdK10byDzTK8eaC8lhijpw639aIXX9YehF1UGPTD+vgvOOkuk219ex98vAU5A4jvmz9TLOx//270RHNpRnH9wF+A+QZRjyBwp7Xi8Thc1yzmVwK7yL6B+0pvGWhAvDiVrLhkcWJrS7rOe8j9RqJdWrXZIQmfdSfm0FfvVTgea86hOz4WNt4fwhg0CVi8e5oHwrX8eK0oVnYkOP+8zy/k6dF+0w4wMwltEEwPKzbwQyPuMbQtX3UqpZYYU5eQVDZ3UeMh62zJWtKPZZPLLTcq06wQs0NXuh7XNUqqap2AGTd0xsKiczKzFo/oAjGSSVY="
      

script:
  - sonar-scanner








  

