language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies
# install:
#   - pip freeze > requirements.txt

 install:
   - pip install -r requirements.txt
   - pip install pytest
   - pip install codecov
   - pip install pytest-cov
 script:
   - pytest --cov-report term --cov=backend backend/UnitTests/ 
# after_success: 
#     - codecov

addons:
  sonarcloud:
    organization: "csc47300-project"
    token:
      secure: "71f410c39da186b1249db45940f2fbd290fedca1" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  
# script:
#   - echo "Hello, World!"
  
# # allow gui output
# services:
#   - xvfb
  

